#CREATE DATABASE io_course_day3

DROP TABLE IF EXISTS Employee;

CREATE TABLE Employee
(
	employee_ID int AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) UNIQUE NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO Employee VALUES (0, "Employee 1", DEFAULT);
INSERT INTO Employee VALUES (0, "Employee 2", DEFAULT);
